[plugin]
name = "gen_makepad_http"
authors = ["syf<syf20020816@outlook.com>"]
version = "0.1.0"
description = "http support for makepad"
category = "network"
repo = { git = "https://github.com/Privoce/genui_plugins/tree/main/projects/gen_makepad_http" }

[macros]
http_get = { category = "prop_macro", stmts = 'if mac . ident == "http_get" { mac . tokens . push_str (", cx") ; }' }
